on:
  push:
     branches:
       - main

name: Deploy app to shinyapps.io

jobs:
  deploy-shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        
    steps:
       - name: 🛎️ Checkout repository
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - id: deploy
         name: 💎 Deploy to shinyapps.io
         uses: qwert666/shinyapps-actions@main
         env:
           SHINY_USERNAME: 'albersonmiranda'
           SHINY_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
           SHINY_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
           APP_NAME: 'Globl_Biodiversity'
           APP_DIR: 'src'